Ruby on Rails Microverse Forms
lucasmazo32/re-former pull request #1
Opened 2020-01-23 17:53 UTC by rkyankya

2020-01-25 04:07 UTC, Ispirett requested changes
## Status Changes Required! :+1: 
Great  Job so far @rkyankya  @lucasmazo32 
There is just one thing missing.
- [ ] You need to have a plain html form also [check](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/rails/forms/user_form1.png)

2020-01-26 19:09 UTC, ebukaume requested changes
## Changes Required! :stop_sign: 

Hi @rkyankya and @lucasmazo32 :wave: 

Nice work so far, but there are a few things we need to take care of. 

* [x] It is possible to create a new user in app. ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/rails/forms/create_new_user.png) from [Odin](https://www.theodinproject.com/courses/ruby-on-rails/lessons/forms))
* [x] it is possible to edit a user in app. ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/rails/forms/edit_user.png) from [Odin](https://www.theodinproject.com/courses/ruby-on-rails/lessons/forms))

_I was unable to do either. Did you test the app?_

**For your views, you need to have:**
- [x] Commented out `form`, ([screenshot 1](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/rails/forms/user_form1.png) [screenshot 2](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/rails/forms/user_form2.png) from [Odin](https://www.theodinproject.com/courses/ruby-on-rails/lessons/forms))

- [x] Commented out `form_tag` that uses `label_tag`, `text_field_tag`, `email_field_tag`, `password_field_tag` ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/rails/forms/user_form_tag2.png) from [Odin](https://www.theodinproject.com/courses/ruby-on-rails/lessons/forms))

- [x] `form_for` that uses `@user` from controller ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/rails/forms/user_form_for.png) from [Odin](https://www.theodinproject.com/courses/ruby-on-rails/lessons/forms))

- [x] The same applies, also, to `edit` ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/rails/forms/user_form_edit.png) from [Odin](https://www.theodinproject.com/courses/ruby-on-rails/lessons/forms))

**Kindly submit another code review after fixing these issues**

Happy Coding :v: 
**Ebuka Umeokonkwo**
 [Github](https://github.com/ebukaume) | [Linkedin](https://www.linkedin.com/in/ebukaume) | [Slack](https://app.slack.com/team/UFDKXE68L) | [Twitter](https://twitter.com/ebukaume)

2020-01-26 19:09 UTC, ebukaume commented on app/views/users/edit.html.erb
> +  <input type="hidden" name="authenticity_token" value="NRkFyRWxdYNfUg7vYxLOp2SLf93lvnl+QwDWorR42Dp6yZXPhHEb6arhDOIWcqGit8jfnrPwL781/xlrzj63TA==" />
Authenticity token should be dynamically generated

2020-01-26 19:09 UTC, ebukaume commented on app/views/users/new.html.erb
> +      <input type="hidden" name="authenticity_token" value="NRkFyRWxdYNfUg7vYxLOp2SLf93lvnl+QwDWorR42Dp6yZXPhHEb6arhDOIWcqGit8jfnrPwL781/xlrzj63TA==" />
Same as above

2020-01-27 00:53 UTC, Ispirett approved these changes
Status Approved 👍 
Great @rkyankya  @ebukaume  work you can merge now!

2020-01-27 04:54 UTC, merged